# Server Port Configuration
server.port=8080

# Spring JPA & H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:turfdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Prevent app crash on startup
spring.main.allow-bean-definition-overriding=true